{
 "title": "DevOps App Monitoring.",
 "description": "Monitoring dashboard for Kubernetes DevOps application showing CPU, memory, and pod metrics using Prometheus and Grafana.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Receive ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top 5 CPU Consuming Pods",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Transmit Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"default\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}